Document: netforward
Title: Debian netforward Manual
Author: <insert document author here>
Abstract: This manual describes what netforward is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/netforward/netforward.sgml.gz

Format: postscript
Files: /usr/share/doc/netforward/netforward.ps.gz

Format: text
Files: /usr/share/doc/netforward/netforward.text.gz

Format: HTML
Index: /usr/share/doc/netforward/html/index.html
Files: /usr/share/doc/netforward/html/*.html

  
